/-
================================================================
Towers / Attempts / OSHilbert  (Batch 19.1b — sorry-bearing stubs)

**THIS FILE IS NOT A BRICK.** It is deliberately excluded from the
BRICKS array in `scripts/check-towers.sh`. Every theorem here is
`sorry`-backed and pins a hard surface that the real OS
reconstruction would discharge, but that the current skeleton
cannot. Each surface is a target for a future batch; none of them
contribute to the wall count.

The presence of `sorry` here does NOT pollute the BRICKS axiom
footprint: the verifier file generated by `check-towers.sh` only
runs `#print axioms` on the names listed in BRICKS, and these
three names are not in BRICKS.

## What this file pins

Three theorems the full OS reconstruction would discharge for the
Wilson SU(3) action; their *statements* are real (they reference
real fields of `OSPreHilbert`); their *proofs* are `sorry`:

  * `OS_positivity_for_Wilson` — the Wilson action yields a
    reflection-positive `OSPreHilbert`. Osterwalder–Seiler 1978.
  * `Transfer_bounded` — the (named, abstract) transfer operator
    `T_g : ℋ_phys → ℋ_phys` is bounded.
  * `Transfer_compact` — the transfer operator is compact (the
    real surface that yields a spectral gap for SU(3)).

## Honest-scope reminder

YM tower stays `Status: Open` (`docs/ROADMAP.md` § 2). The
`sorry`-bearing statements below do NOT certify, prove, or
discharge any tower. They are placeholders that fail-fast at
build time (Lean prints a warning per `sorry`) so that the next
batch knows exactly which surface still owes a real proof.

================================================================
-/

import Towers.YM.OSReconstruction

namespace TheoremaAureum
namespace Towers
namespace Attempts
namespace OSHilbert

open TheoremaAureum.Towers.YM.OSReconstruction

/- **OS positivity for the Wilson SU(3) action.**

For a concrete Wilson `OSPreHilbert` datum `D` (which we do not
construct here), the reflection-positivity property
`D.reflectionPositive` holds. This is Osterwalder–Seiler 1978 for
SU(N) Wilson, and is OUT OF SCOPE for the current OS-skeleton
batches. -/
/-- Named-open surface behind `OS_positivity_for_Wilson` (Osterwalder–Seiler 1978
reflection positivity for SU(N) Wilson). Stated as a `Prop`, NOT `by sorry`. -/
def OS_positivity_for_Wilson_Surface (D : OSPreHilbert) : Prop :=
  D.reflectionPositive

theorem OS_positivity_for_Wilson (D : OSPreHilbert)
    (h : OS_positivity_for_Wilson_Surface D) :
    D.reflectionPositive := h

/- **Transfer-operator boundedness.**

For a concrete `OSPreHilbert` datum `D` arising from a
reflection-positive lattice action, the (named, abstract) transfer
operator `T_g : ℋ_phys → ℋ_phys` carrying the time-translation
group is bounded. Statement is pinned at the NAMED-Prop level
`D.timeZeroAlgebra_acts` until 19.1c lands a real
`TransferOperator` bundle. -/
/-- Named-open surface behind `Transfer_bounded`. Stated as a `Prop`, NOT
`by sorry`. -/
def Transfer_bounded_Surface (D : OSPreHilbert) : Prop :=
  D.timeZeroAlgebra_acts

theorem Transfer_bounded (D : OSPreHilbert)
    (h : Transfer_bounded_Surface D) :
    D.timeZeroAlgebra_acts := h

/- **Transfer-operator compactness.**

Strengthening of `Transfer_bounded`: the transfer operator is in
fact compact (the real spectral-gap-yielding surface for SU(3)
Wilson). Statement is pinned at the NAMED-Prop level
`D.physHilbert_isHilbert` until 19.1d lands a real
`CompactOperator` predicate. -/
/-- Named-open surface behind `Transfer_compact` (transfer-operator compactness,
the real spectral-gap-yielding surface for SU(3) Wilson). Stated as a `Prop`,
NOT `by sorry`. -/
def Transfer_compact_Surface (D : OSPreHilbert) : Prop :=
  D.physHilbert_isHilbert

theorem Transfer_compact (D : OSPreHilbert)
    (h : Transfer_compact_Surface D) :
    D.physHilbert_isHilbert := h

end OSHilbert
end Attempts
end Towers
end TheoremaAureum
